### ISSUE TITLE
Add angular material to

### ISSUE THREAD

**Issue by madox357** [madox357/artemas#1]
## TODO

- [ ] Add angular material
- [ ] Create a home component
- [ ] Add side navigation (fixed)
- [ ] Add top toolbar (fixed)
